%% From |example2| in the WyFy distribution

%%
clear
fig = figure(1);
clf(fig, 'reset')

%% New representation
scenedata = num2cell([
    0, 0, 15, 0, -3;
    15, 0, 15, 8, -3;
    15, 8, 0, 8, -3;
    0, 8, 0, 0, -3;
    5, 0, 5, 4, -3;
    10, 0, 10, 4, -20;  % Concrete wall
    ], 1);
[faces, vertices] = data.linestofacevertex(scenedata{1 : 4});
transmissiongains = scenedata{5};
reflectiongains = repmat(realmin, size(transmissiongains));
scene = scenes.Scene(faces, vertices);
accesspoints = struct( ...
    'Position', [1, 1; 14, 1; 10, 6], ...
    'Gain', [3.2; 1.3; 2.1], ...
    'Channel', [1; 2; 1]);
mobiles = struct( ...
    'Position', [5, 5; 11, 2], ...
    'Gain', [1.7; 0.9]);

%% Initialise wyfy system, 
model = interactive.Interactive( ...
    faces, vertices, ...
    accesspoints.Position, ...
    mobiles.Position, ...
    'AccessPointGains', accesspoints.Gain, ...
    'AccessPointChannels', accesspoints.Channel, ...
    'MobileGains', mobiles.Gain, ...
    'TransmissionGain', transmissiongains, ...
    'FigureHandle', fig, ...
    'Quiet', false, ...
    'NumContourMapSamples', 10, ...
    'ReflectionArity', 0);
