function tableout = level8locations(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   DATA = IMPORTFILE(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as a
%   table.
%
%   DATA = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   level8locsreport = importfile('level8locs-report.xlsx','Sheet1',3,182);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2017/08/29 09:51:14

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 3;
    endRow = 182;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('A%d:H%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:H%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
stringVectors = string(raw(:,[1,2,3,5,6,7,8]));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,4);

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Create table
tableout = table;

%% Allocate imported array to column variable names
tableout.DisplayedText = cellstr(stringVectors(:,1));
tableout.Height = categorical(stringVectors(:,2));
tableout.MasterName = cellstr(stringVectors(:,3));
tableout.ShapeID = data(:,1);
tableout.ShapeName = cellstr(stringVectors(:,4));
tableout.Width = categorical(stringVectors(:,5));
tableout.XLocation = cellstr(stringVectors(:,6));
tableout.YLocation = categorical(stringVectors(:,7));

