function [dlinks, ulinks, hits, durations] = ...
    analyze(reflect, transmit, numfacets, origins, targets, varargin)

[traceoptions, unmatched] = imagemethod.tracesceneSettings(varargin{:});

% Augment optional settings
parser = inputParser;
parser.addParameter( ...
    'AccessPointChannel', ...
    ones(size(origins, 1), 1), ...
    @(c) isnumeric(c) && numel(c) == size(origins, 1) && 1 <= min(c(:)))
parser.addParameter( ...
    'MinimumDiscernableSignal', ...
    minimumdiscernablesignal, ... % [dBW]
    @(x) isnumeric(x) && isscalar(x) && x < 0)
parser.parse(unmatched)
linkoptions = parser.Results;

[downlinks, uplinks, hits, durations] = ...
    imagemethod.tracescene( ...
    reflect, transmit, numfacets, origins, targets, traceoptions);

% Received gain (in dBW): Rows for access points, columns for mobiles
downlinksDBW = specfun.todb(sum(downlinks, 3));

% Downlink calculations
dlinks = power.dlinksinr( ...
    downlinksDBW, ...
    linkoptions.AccessPointChannel, ...
    linkoptions.MinimumDiscernableSignal);
dlinks.PowerComponentsWatts = downlinks;
dlinks.PowerDBW = downlinksDBW;

dlinks = orderfields(dlinks, {
    'PowerDBW' ...
    'PowerComponentsWatts' ...
    'SINRatio' ...
    'INGainDBW' ...
    'SGainDBW' ...
    'AccessPoint' ...
    'Channel' ...
    });

if nargout < 2
    return % uplink calculations are not required
end

% Received gain (in watts), rows for receivers
uplinkgainwatts = sum(uplinks, 3);
uplinkgaindbw = specfun.todb(uplinkgainwatts);

% Uplink calculations
ulinks = power.ulinksinr( ...
    uplinkgaindbw, ...
    dlinks.AccessPoint, ...
    linkoptions.AccessPointChannel, ...
    linkoptions.MinimumDiscernableSignal);
ulinks.PowerComponentsWatts = uplinks;
ulinks.PowerDBW = uplinkgaindbw;

ulinks = orderfields(ulinks, {
    'PowerDBW' ...
    'PowerComponentsWatts' ...
    'SINRatio' ...
    'INGainDBW' ...
    'SGainDBW' ...
    });

% -------------------------------------------------------------------------
function mds = minimumdiscernablesignal(options)
% MINIMUMDISCERNABLESIGNAL Minimum discernable signal in dBw

if nargin == 1
    assert(isstruct(options))
    fieldname = 'MinimumDiscernableSignal';
    if isfield(options, fieldname)
        mds = options.(fieldname);
        return
    end
end

mds = -100; % [dBW]
