function stats = interactionstatistics(interactiontypes)

count = @(type) sum(imagemethod.interaction.(type) == interactiontypes);
numsources = count('Source');
numsinks = count('Sink');
numreflected = count('Reflection');
numtransmitted = count('Transmission');

numnodes = numel(interactiontypes);
absrel = @(n) [n; n/numnodes];

stats = struct( ...
    'Measure', {{'Absolute'; 'Relative'}}, ...
    'Source', absrel(numsources), ...
    'Sink', absrel(numsinks), ...
    'Reflection', absrel(numreflected), ...
    'Transmission', absrel(numtransmitted), ...
    'All', absrel(numnodes));
