function result = isfvframe(f)
%ISFVFRAME True for unit frames stored by rows.
% See also FVFRAMES.
unit = 1.0;
tol = eps(10*unit); % relative to 1.0
result = ...
    isnumeric(f) ...
    && ndims(f) == 3 ...
    && ismember(size(f, 2), 2 : 3) ...
    && size(f, 2) == size(f, 3) ...
    && all(vec(abs(twonorm(f, 2) - unit)) < tol);
